/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analysis-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis Job */
        get: operations["getAnalysisJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-jobs/{job_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Analysis Result */
        get: operations["exportAnalysisResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis Result */
        get: operations["getAnalysisResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-jobs/{job_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analysis */
        post: operations["runAnalysisJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participant-sessions/{session_id}/calibrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Calibration */
        post: operations["recordCalibrationResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participant-sessions/{session_id}/consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Consent */
        post: operations["recordParticipantConsent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participant-sessions/{session_id}/gaze-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Gaze Batch */
        post: operations["ingestGazeBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participant-sessions/{session_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Participant Session */
        post: operations["submitParticipantSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participant-sessions/{session_id}/task-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Task Run */
        post: operations["startTaskRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participant-sessions/{session_id}/task-runs/{task_run_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Task Run */
        post: operations["completeTaskRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participate/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Participant Link */
        get: operations["resolveParticipantLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participate/{token}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Participant Session */
        post: operations["createParticipantSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["listProjects"];
        put?: never;
        /** Create Project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["updateProject"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/studies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Studies */
        get: operations["listStudies"];
        put?: never;
        /** Create Study */
        post: operations["createStudy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Study */
        delete: operations["deleteStudy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/analysis-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Study Analysis Jobs */
        get: operations["listStudyAnalysisJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Study Draft */
        get: operations["getStudyDraft"];
        /** Replace Study Draft */
        put: operations["replaceStudyDraft"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/participant-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Participant Link */
        get: operations["getActiveParticipantLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/participant-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Study Participant Sessions */
        get: operations["listStudyParticipantSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Study */
        post: operations["publishStudy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/synthetic-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Synthetic Study Results */
        post: operations["createSyntheticStudyResults"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/studies/{study_id}/versions/{version_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Study Version */
        get: operations["getStudyVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisJobListResponse */
        AnalysisJobListResponse: {
            /** Items */
            items: components["schemas"]["AnalysisJobResponse"][];
            /** Total */
            total: number;
        };
        /** AnalysisJobResponse */
        AnalysisJobResponse: {
            /** Algorithm Version */
            algorithm_version: string;
            /** Attempt */
            attempt: number;
            /** Error Code */
            error_code: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Parameters */
            parameters: {
                [key: string]: unknown;
            };
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["AnalysisStatus"];
        };
        /** AnalysisResultResponse */
        AnalysisResultResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Diagnostics */
            diagnostics: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /** Quality */
            quality: {
                [key: string]: unknown;
            };
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Task Metrics */
            task_metrics: {
                [key: string]: unknown;
            };
        };
        /**
         * AnalysisStatus
         * @enum {string}
         */
        AnalysisStatus: "queued" | "running" | "succeeded" | "failed";
        /** AreaOfInterestDraft */
        AreaOfInterestDraft: {
            /** Height */
            height?: number | null;
            /** Label */
            label: string;
            /** Page Path */
            page_path?: string | null;
            /** Selector */
            selector?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "manual" | "selector" | "imported";
            /** Width */
            width?: number | null;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
        };
        /** CalibrationPolicy */
        CalibrationPolicy: {
            /**
             * Allow Retry
             * @default true
             */
            allow_retry: boolean;
            /**
             * Maximum Attempts
             * @default 3
             */
            maximum_attempts: number;
            /**
             * Minimum Quality
             * @default variable
             * @enum {string}
             */
            minimum_quality: "strong" | "variable" | "limited";
        };
        /** CalibrationResultCreate */
        CalibrationResultCreate: {
            /** Attempt */
            attempt: number;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Diagnostics */
            diagnostics?: {
                [key: string]: unknown;
            };
            /** Error Px */
            error_px?: number | null;
            /** Observed Sample Count */
            observed_sample_count: number;
            quality_grade: components["schemas"]["QualityGrade"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Target Count */
            target_count: number;
        };
        /** CalibrationResultResponse */
        CalibrationResultResponse: {
            /** Accepted */
            accepted: boolean;
            /** Attempt */
            attempt: number;
            /** Attempts Remaining */
            attempts_remaining: number;
            /** Error Px */
            error_px: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            lifecycle: components["schemas"]["SessionLifecycle"];
            /** Observed Sample Count */
            observed_sample_count: number;
            quality_grade: components["schemas"]["QualityGrade"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Target Count */
            target_count: number;
        };
        /** CollectionPolicy */
        CollectionPolicy: {
            /**
             * Sample Interval Ms
             * @default 100
             */
            sample_interval_ms: number;
            /**
             * Screenshots Enabled
             * @default false
             */
            screenshots_enabled: boolean;
        };
        /** ConsentCreate */
        ConsentCreate: {
            /**
             * Accepted
             * @constant
             */
            accepted: true;
            /** Consent Version */
            consent_version: string;
        };
        /** ConsentResponse */
        ConsentResponse: {
            /** Consent Version */
            consent_version: string;
            /**
             * Consented At
             * Format: date-time
             */
            consented_at: string;
            lifecycle: components["schemas"]["SessionLifecycle"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Field */
            field?: string | null;
            /** Message */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorDetail"];
            /** Request Id */
            request_id: string;
        };
        /** GazeBatchCreate */
        GazeBatchCreate: {
            /**
             * Captured From
             * Format: date-time
             */
            captured_from: string;
            /**
             * Captured To
             * Format: date-time
             */
            captured_to: string;
            /**
             * Client Batch Id
             * Format: uuid
             */
            client_batch_id: string;
            /** Samples */
            samples: components["schemas"]["GazeSampleCreate"][];
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            /** Sequence */
            sequence: number;
        };
        /** GazeBatchResponse */
        GazeBatchResponse: {
            /**
             * Client Batch Id
             * Format: uuid
             */
            client_batch_id: string;
            /** Highest Sequence Received */
            highest_sequence_received: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Missing Sequences */
            missing_sequences: number[];
            /** Payload Checksum */
            payload_checksum: string;
            /** Replayed */
            replayed: boolean;
            /** Sample Count */
            sample_count: number;
            /** Sequence */
            sequence: number;
        };
        /** GazeSampleCreate */
        GazeSampleCreate: {
            /** Confidence */
            confidence?: number | null;
            /**
             * Scroll X
             * @default 0
             */
            scroll_x: number;
            /**
             * Scroll Y
             * @default 0
             */
            scroll_y: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Viewport Height */
            viewport_height: number;
            /** Viewport Width */
            viewport_width: number;
            /** X Normalized */
            x_normalized: number;
            /** Y Normalized */
            y_normalized: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Service
             * @default webgaze-api
             * @constant
             */
            service: "webgaze-api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** ParticipantLinkResponse */
        ParticipantLinkResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Participant Url */
            participant_url: string;
            /**
             * Study Version Id
             * Format: uuid
             */
            study_version_id: string;
            /** Token */
            token: string;
        };
        /** ParticipantSessionCreate */
        ParticipantSessionCreate: {
            /** Browser Family */
            browser_family?: string | null;
            /**
             * Device Pixel Ratio
             * @default 1
             */
            device_pixel_ratio: number;
            /** Viewport Height */
            viewport_height: number;
            /** Viewport Width */
            viewport_width: number;
        };
        /** ParticipantSessionResponse */
        ParticipantSessionResponse: {
            /** Access Token */
            access_token?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            lifecycle: components["schemas"]["SessionLifecycle"];
            /** Participant Alias */
            participant_alias: string;
            /**
             * Retention Expires At
             * Format: date-time
             */
            retention_expires_at: string;
        };
        /** ParticipantSessionSummary */
        ParticipantSessionSummary: {
            analysis_status: components["schemas"]["AnalysisStatus"] | null;
            /** Calibration Error Px */
            calibration_error_px: number | null;
            calibration_quality: components["schemas"]["QualityGrade"] | null;
            /** Completed Task Count */
            completed_task_count: number;
            /** Consented At */
            consented_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Events */
            events: components["schemas"]["SessionTimelineEvent"][];
            /** Gaze Batch Count */
            gaze_batch_count: number;
            /** Gaze Sample Count */
            gaze_sample_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            lifecycle: components["schemas"]["SessionLifecycle"];
            /** Participant Alias */
            participant_alias: string;
            /** Source */
            source: string;
            /** Submitted At */
            submitted_at: string | null;
        };
        /** ParticipantSessionSummaryListResponse */
        ParticipantSessionSummaryListResponse: {
            /** Items */
            items: components["schemas"]["ParticipantSessionSummary"][];
            /** Total */
            total: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Research Question */
            research_question?: string | null;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Items */
            items: components["schemas"]["ProjectResponse"][];
            /** Total */
            total: number;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Owner Id
             * Format: uuid
             */
            owner_id: string;
            /** Research Question */
            research_question: string | null;
            status: components["schemas"]["ProjectStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "active" | "archived";
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Research Question */
            research_question?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
        };
        /** PublicStudyProtocol */
        PublicStudyProtocol: {
            calibration_policy: components["schemas"]["CalibrationPolicy"];
            collection_policy: components["schemas"]["CollectionPolicy"];
            /** Consent Text */
            consent_text: string;
            /** Consent Version */
            consent_version: string;
            /** Target Origins */
            target_origins: string[];
            /** Tasks */
            tasks: components["schemas"]["PublicTask"][];
            /** Title */
            title: string;
        };
        /** PublicTask */
        PublicTask: {
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
            /**
             * Start Url
             * Format: uri
             */
            start_url: string;
            /** Success Url Pattern */
            success_url_pattern: string | null;
            /** Time Limit Ms */
            time_limit_ms: number | null;
            /** Title */
            title: string;
        };
        /** PublishResponse */
        PublishResponse: {
            participant_link?: components["schemas"]["ParticipantLinkResponse"] | null;
            /**
             * Replayed
             * @default false
             */
            replayed: boolean;
            study: components["schemas"]["StudySummary"];
            version: components["schemas"]["StudyVersionResponse"];
        };
        /**
         * QualityGrade
         * @enum {string}
         */
        QualityGrade: "strong" | "variable" | "limited" | "failed";
        /**
         * SessionLifecycle
         * @enum {string}
         */
        SessionLifecycle: "created" | "consented" | "calibrating" | "ready" | "running" | "paused" | "submitted" | "withdrawn" | "expired" | "abandoned";
        /** SessionSubmitResponse */
        SessionSubmitResponse: {
            analysis_job: components["schemas"]["AnalysisJobResponse"];
            lifecycle: components["schemas"]["SessionLifecycle"];
            /** Replayed */
            replayed: boolean;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** SessionTimelineEvent */
        SessionTimelineEvent: {
            /** Kind */
            kind: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** StudyCreate */
        StudyCreate: {
            calibration_policy?: components["schemas"]["CalibrationPolicy"];
            collection_policy?: components["schemas"]["CollectionPolicy"];
            /** Consent Text */
            consent_text: string;
            /** Consent Version */
            consent_version: string;
            /** Description */
            description?: string | null;
            /**
             * Retention Days
             * @default 30
             */
            retention_days: number;
            /** Target Origins */
            target_origins: string[];
            /** Tasks */
            tasks: components["schemas"]["TaskDraft"][];
            /** Title */
            title: string;
        };
        /** StudyDraft */
        StudyDraft: {
            calibration_policy?: components["schemas"]["CalibrationPolicy"];
            collection_policy?: components["schemas"]["CollectionPolicy"];
            /** Consent Text */
            consent_text: string;
            /** Consent Version */
            consent_version: string;
            /** Description */
            description?: string | null;
            /**
             * Retention Days
             * @default 30
             */
            retention_days: number;
            /** Target Origins */
            target_origins: string[];
            /** Tasks */
            tasks: components["schemas"]["TaskDraft"][];
            /** Title */
            title: string;
        };
        /** StudyDraftResponse */
        StudyDraftResponse: {
            calibration_policy?: components["schemas"]["CalibrationPolicy"];
            collection_policy?: components["schemas"]["CollectionPolicy"];
            /** Consent Text */
            consent_text: string;
            /** Consent Version */
            consent_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Published Version */
            current_published_version: number | null;
            /** Description */
            description?: string | null;
            /** Draft Revision */
            draft_revision: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            lifecycle: components["schemas"]["StudyLifecycle"];
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Retention Days
             * @default 30
             */
            retention_days: number;
            /** Target Origins */
            target_origins: string[];
            /** Tasks */
            tasks: components["schemas"]["TaskDraft"][];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * StudyLifecycle
         * @enum {string}
         */
        StudyLifecycle: "draft" | "published" | "closed" | "archived";
        /** StudyListResponse */
        StudyListResponse: {
            /** Items */
            items: components["schemas"]["StudySummary"][];
            /** Total */
            total: number;
        };
        /** StudySummary */
        StudySummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Published Version */
            current_published_version: number | null;
            /** Draft Revision */
            draft_revision: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            lifecycle: components["schemas"]["StudyLifecycle"];
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StudyVersionResponse */
        StudyVersionResponse: {
            calibration_policy?: components["schemas"]["CalibrationPolicy"];
            collection_policy?: components["schemas"]["CollectionPolicy"];
            /** Consent Text */
            consent_text: string;
            /** Consent Version */
            consent_version: string;
            /** Description */
            description?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * Published By
             * Format: uuid
             */
            published_by: string;
            /**
             * Retention Days
             * @default 30
             */
            retention_days: number;
            /** Source Revision */
            source_revision: number;
            /**
             * Study Id
             * Format: uuid
             */
            study_id: string;
            /** Target Origins */
            target_origins: string[];
            /** Tasks */
            tasks: components["schemas"]["TaskDraft"][];
            /** Title */
            title: string;
            /** Version Number */
            version_number: number;
        };
        /** TaskDraft */
        TaskDraft: {
            /** Areas Of Interest */
            areas_of_interest?: components["schemas"]["AreaOfInterestDraft"][];
            /** Position */
            position: number;
            /** Prompt */
            prompt: string;
            /**
             * Start Url
             * Format: uri
             */
            start_url: string;
            /** Success Url Pattern */
            success_url_pattern?: string | null;
            /** Time Limit Ms */
            time_limit_ms?: number | null;
            /** Title */
            title: string;
        };
        /**
         * TaskOutcome
         * @enum {string}
         */
        TaskOutcome: "running" | "completed" | "skipped" | "timed_out";
        /** TaskRunComplete */
        TaskRunComplete: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "completed" | "skipped" | "timed_out";
        };
        /** TaskRunCreate */
        TaskRunCreate: {
            /** Task Position */
            task_position: number;
        };
        /** TaskRunResponse */
        TaskRunResponse: {
            /** Ended At */
            ended_at: string | null;
            /** First Sequence */
            first_sequence: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Sequence */
            last_sequence: number | null;
            outcome: components["schemas"]["TaskOutcome"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            session_lifecycle: components["schemas"]["SessionLifecycle"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Task Position */
            task_position: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAnalysisJob: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJobResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    exportAnalysisResult: {
        parameters: {
            query?: {
                format?: "json" | "csv";
            };
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getAnalysisResult: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResultResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runAnalysisJob: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResultResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recordCalibrationResult: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationResultCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationResultResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recordParticipantConsent: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingestGazeBatch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GazeBatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GazeBatchResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitParticipantSession: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSubmitResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    startTaskRun: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completeTaskRun: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                task_run_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskRunComplete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRunResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolveParticipantLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicStudyProtocol"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createParticipantSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantSessionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gone */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listStudies: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createStudy: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyDraftResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteStudy: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listStudyAnalysisJobs: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJobListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStudyDraft: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyDraftResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replaceStudyDraft: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudyDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyDraftResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getActiveParticipantLink: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantLinkResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listStudyParticipantSessions: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantSessionSummaryListResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publishStudy: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                "x-demo-owner-id"?: string | null;
            };
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createSyntheticStudyResults: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                study_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResultResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStudyVersion: {
        parameters: {
            query?: never;
            header?: {
                "x-demo-owner-id"?: string | null;
            };
            path: {
                study_id: string;
                version_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudyVersionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
