"""initial domain model

Revision ID: 60c5c5f19d16
Revises:
Create Date: 2026-09-04 17:56:40.890018
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "60c5c5f19d16"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_resource_id"), "audit_events", ["resource_id"], unique=False
    )
    op.create_table(
        "research_projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("research_question", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "ARCHIVED", name="projectstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_projects_owner_id"), "research_projects", ["owner_id"], unique=False
    )
    op.create_table(
        "studies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "lifecycle",
            sa.Enum(
                "DRAFT", "PUBLISHED", "CLOSED", "ARCHIVED", name="studylifecycle", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("draft_revision", sa.Integer(), nullable=False),
        sa.Column("current_published_version", sa.Integer(), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["research_projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_studies_project_id"), "studies", ["project_id"], unique=False)
    op.create_table(
        "study_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("consent_version", sa.String(length=40), nullable=False),
        sa.Column("consent_text", sa.Text(), nullable=False),
        sa.Column("target_origins", sa.JSON(), nullable=False),
        sa.Column("calibration_policy", sa.JSON(), nullable=False),
        sa.Column("collection_policy", sa.JSON(), nullable=False),
        sa.Column("retention_days", sa.Integer(), nullable=False),
        sa.Column("published_by", sa.Uuid(), nullable=False),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["study_id"], ["studies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_id", "version_number"),
    )
    op.create_index(
        op.f("ix_study_versions_study_id"), "study_versions", ["study_id"], unique=False
    )
    op.create_table(
        "participant_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_version_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("max_sessions", sa.Integer(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["study_version_id"], ["study_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_participant_links_study_version_id"),
        "participant_links",
        ["study_version_id"],
        unique=False,
    )
    op.create_table(
        "participant_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_version_id", sa.Uuid(), nullable=False),
        sa.Column("participant_alias", sa.String(length=80), nullable=False),
        sa.Column(
            "lifecycle",
            sa.Enum(
                "CREATED",
                "CONSENTED",
                "CALIBRATING",
                "READY",
                "RUNNING",
                "PAUSED",
                "SUBMITTED",
                "WITHDRAWN",
                "EXPIRED",
                "ABANDONED",
                name="sessionlifecycle",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("consent_version", sa.String(length=40), nullable=True),
        sa.Column("consented_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("browser_family", sa.String(length=40), nullable=True),
        sa.Column("viewport_width", sa.Integer(), nullable=True),
        sa.Column("viewport_height", sa.Integer(), nullable=True),
        sa.Column("device_pixel_ratio", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("last_sequence_received", sa.Integer(), nullable=True),
        sa.Column("retention_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["study_version_id"], ["study_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_participant_sessions_study_version_id"),
        "participant_sessions",
        ["study_version_id"],
        unique=False,
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("study_version_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("start_url", sa.Text(), nullable=False),
        sa.Column("success_url_pattern", sa.Text(), nullable=True),
        sa.Column("time_limit_ms", sa.Integer(), nullable=True),
        sa.CheckConstraint("position >= 1 AND position <= 4", name="ck_task_position_1_4"),
        sa.ForeignKeyConstraint(["study_version_id"], ["study_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("study_version_id", "position"),
    )
    op.create_index(op.f("ix_tasks_study_version_id"), "tasks", ["study_version_id"], unique=False)
    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "RUNNING", "SUCCEEDED", "FAILED", name="analysisstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column(
            "queued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["participant_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "algorithm_version", "attempt"),
    )
    op.create_index(
        op.f("ix_analysis_jobs_session_id"), "analysis_jobs", ["session_id"], unique=False
    )
    op.create_table(
        "areas_of_interest",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("x", sa.Numeric(precision=8, scale=7), nullable=True),
        sa.Column("y", sa.Numeric(precision=8, scale=7), nullable=True),
        sa.Column("width", sa.Numeric(precision=8, scale=7), nullable=True),
        sa.Column("height", sa.Numeric(precision=8, scale=7), nullable=True),
        sa.Column("selector", sa.Text(), nullable=True),
        sa.Column("page_path", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_areas_of_interest_task_id"), "areas_of_interest", ["task_id"], unique=False
    )
    op.create_table(
        "calibration_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("observed_sample_count", sa.Integer(), nullable=False),
        sa.Column("error_px", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column(
            "quality_grade",
            sa.Enum(
                "STRONG", "VARIABLE", "LIMITED", "FAILED", name="qualitygrade", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("diagnostics", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["participant_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "attempt"),
    )
    op.create_index(
        op.f("ix_calibration_results_session_id"),
        "calibration_results",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "gaze_sample_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_batch_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("captured_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("payload_checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["participant_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "client_batch_id"),
        sa.UniqueConstraint("session_id", "sequence"),
    )
    op.create_index(
        op.f("ix_gaze_sample_batches_session_id"),
        "gaze_sample_batches",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "task_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "RUNNING",
                "COMPLETED",
                "SKIPPED",
                "TIMED_OUT",
                name="taskoutcome",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_sequence", sa.Integer(), nullable=True),
        sa.Column("last_sequence", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["participant_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_one_running_task_per_session",
        "task_runs",
        ["session_id"],
        unique=True,
        postgresql_where=sa.text("outcome = 'RUNNING'"),
        sqlite_where=sa.text("outcome = 'RUNNING'"),
    )
    op.create_index(op.f("ix_task_runs_session_id"), "task_runs", ["session_id"], unique=False)
    op.create_table(
        "analysis_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("quality", sa.JSON(), nullable=False),
        sa.Column("task_metrics", sa.JSON(), nullable=False),
        sa.Column("fixations", sa.JSON(), nullable=False),
        sa.Column("aoi_metrics", sa.JSON(), nullable=False),
        sa.Column("diagnostics", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["analysis_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["participant_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    op.create_index(
        op.f("ix_analysis_results_session_id"), "analysis_results", ["session_id"], unique=False
    )
    op.create_table(
        "gaze_samples",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("offset", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("x_normalized", sa.Numeric(precision=8, scale=7), nullable=False),
        sa.Column("y_normalized", sa.Numeric(precision=8, scale=7), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("scroll_x", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("scroll_y", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("viewport_width", sa.Integer(), nullable=False),
        sa.Column("viewport_height", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["batch_id"], ["gaze_sample_batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_id", "offset"),
    )
    op.create_index(op.f("ix_gaze_samples_batch_id"), "gaze_samples", ["batch_id"], unique=False)
    op.create_table(
        "session_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("task_run_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["participant_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_run_id"], ["task_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_events_session_id"), "session_events", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_events_session_id"), table_name="session_events")
    op.drop_table("session_events")
    op.drop_index(op.f("ix_gaze_samples_batch_id"), table_name="gaze_samples")
    op.drop_table("gaze_samples")
    op.drop_index(op.f("ix_analysis_results_session_id"), table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_index(op.f("ix_task_runs_session_id"), table_name="task_runs")
    op.drop_index("uq_one_running_task_per_session", table_name="task_runs")
    op.drop_table("task_runs")
    op.drop_index(op.f("ix_gaze_sample_batches_session_id"), table_name="gaze_sample_batches")
    op.drop_table("gaze_sample_batches")
    op.drop_index(op.f("ix_calibration_results_session_id"), table_name="calibration_results")
    op.drop_table("calibration_results")
    op.drop_index(op.f("ix_areas_of_interest_task_id"), table_name="areas_of_interest")
    op.drop_table("areas_of_interest")
    op.drop_index(op.f("ix_analysis_jobs_session_id"), table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    op.drop_index(op.f("ix_tasks_study_version_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(
        op.f("ix_participant_sessions_study_version_id"), table_name="participant_sessions"
    )
    op.drop_table("participant_sessions")
    op.drop_index(op.f("ix_participant_links_study_version_id"), table_name="participant_links")
    op.drop_table("participant_links")
    op.drop_index(op.f("ix_study_versions_study_id"), table_name="study_versions")
    op.drop_table("study_versions")
    op.drop_index(op.f("ix_studies_project_id"), table_name="studies")
    op.drop_table("studies")
    op.drop_index(op.f("ix_research_projects_owner_id"), table_name="research_projects")
    op.drop_table("research_projects")
    op.drop_index(op.f("ix_audit_events_resource_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
